server:
  port: 8989

spring:
  devtools:
    livereload:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
      url: jdbc:mysql://localhost:3306/play_code_basic
      username: root
      password:

feign:
    hystrix:
        enabled: true